<?php

/**
 * @file
 * Pushes content from one site to another using RESTful web services.
 */


/**
 * Implements hook_help().
 */
function content_direct_help($route_name) {
  switch ($route_name) {
    case 'content_direct.help':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is the help docs for Content Direct, see <a href="!content_direct-module">the online documentation</a></p>');
      return $output;
  }
}


/**
 * Implements hook_node_insert().
 */
function content_direct_node_insert($node) {
  dpm('Insert Hook:');
  $pusher = \Drupal::service('content_direct.content_pusher');
  $data = $pusher->getData($node);
  dpm('data:');
  dpm($data);
  $pusher->request('post', 'entity/node', array('body' => $data));

}

/**
 * Implements hook_node_update().
 */
function content_direct_node_update($node) {
  dpm('Update Hook:');

  $pusher = \Drupal::service('content_direct.content_pusher');
  $data = $pusher->getData($node);
  dpm('data:');
  dpm($data);
  $pusher->request('patch', 'node/' . $node->id(), array('body' => $data));

}
